# Generated by Django 5.1.5 on 2025-01-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('edition', models.CharField(max_length=13)),
                ('published_date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
