# import path, include
from django.urls import path, include

# import DefaultRouter
# https://www.django-rest-framework.org/api-guide/viewsets/#example
from rest_framework.routers import DefaultRouter

# import the BookViewSet class from views.py
from .views import BookViewSet

#######################################################################################

# register the viewset with a router class, that automatically determines the urlconf

# create an instance of the DefaultRouter
router = DefaultRouter()

# register the BookViewSet with the router
# the router will automatically generate URLs for the BookViewSet
# the URLs will be based on the 'books' prefix
# include versioning in the url
# set base to use for the URL names that are created
# https://www.django-rest-framework.org/api-guide/viewsets/#viewset-actions
router.register('books', BookViewSet, basename='books')

# get the URLs generated by the router
# versioning middleware in settings.py processes the version placeholder at the url pattern level
urlpatterns = [
    path('api/v{version}/', include(router.urls))
]